config/routes.rb
Rails.application.routes.draw do
  
  
  resources :clients
  get "/" => "users#home"
  get "/login" => "users#login", :as => "login"
  get "/logout" => "users#logout", :as => "logout"
  post "/users/valid" => "users#valid", :as => "valid"
  
  resources :users
  resources :chores
  
  
  
  
  
  
  
  
  
  
  

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  belongs_to :user
  belongs_to :client
  validates :name, presence: true
  validates :done, presence: true
  validates :user_id, presence: true
  validates :client_id, presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
  
  has_many :chores
  validates :name, presence: true
  validates :email, presence: true
  validates :address, presence: true
 
  # has many appts.
  # has many passwords
  # has many todos
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :chores
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_chore, only: [:show, :edit, :update, :destroy]

  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
  end

  # GET /chores/new
  def new
    @chore = Chore.new
  end

  # GET /chores/1/edit
  def edit
  end

  # POST /chores
  # POST /chores.json
  def create
    
    @user = User.find(params[:chore][:user_id])
    @chore = @user.chores.create(chore_params)
    @chore.save
    redirect_to user_path(@user.id)
  end

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])
    if @chore.done == "false"
      @chore.done ="true"
      @chore.save
      redirect_to user_path(session[:user_id])
    else
      @chore.done ="false"
      @chore.save
      redirect_to user_path(session[:user_id])
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore = Chore.find(params[:id])
    @chore.destroy
    redirect_to user_path(session[:user_id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_chore
    @chore = Chore.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chore_params
    params.require(:chore).permit(:name, :done, :user_id, :client_id)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :address, :notes)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def home
    redirect_to users_path
  end
    
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end
  
  def login
    @user = User.new
  end
  
  def logout
    session[:user_id] = nil
    redirect_to login_path
  end
  # GET /users/1
  # GET /users/1.json
  def show
    if session[:user_id] # && session[:user_id] == params[:id].to_i
      @user = User.find(session[:user_id])
      render :show
    else
      redirect_to login_path
    end
  end
  
  def valid
    @user = User.where(email:params[:user][:email]).first
    if @user.nil?
      @error = true
      redirect_to login_path
    else
      user_password = BCrypt::Password.new(@user.password)
  
      if user_password == params[:user][:password]
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      else
        @error = true
        redirect_to login_path
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if session[:user_id] && session[:user_id] == params[:id].to_i
      @user = User.find(params[:id])
      render :edit
    else
      redirect_to user_path("#{session[:user_id]}")
    end
  end

  # POST /users
  # POST /users.json
  def create
    the_password = BCrypt::Password.create(params[:user][:password])
    @user = User.new(user_params)
    @user.password = the_password
    if @user.save
      redirect_to login_path #should redirect to login after creating profile.
    else
      @error = true
      redirect_to new_user_path
    end
    @user = User.new(user_params)
  end
  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    the_password = BCrypt::Password.create(params[:user][:password])
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    @user.password = the_password
    # if @user.save
    #      redirect_to user_path(@user.id)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.text_field :done %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing Chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Done</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chores.each do |chore| %>
      <tr>
        <td><%= chore.name %></td>
        <td><%= chore.done %></td>
        <td><%= chore.user_id %></td>
        <td><%= link_to 'Show', chore %></td>
        <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
        <td><%= link_to 'Destroy', chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New Chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chore.name %>
</p>

<p>
  <strong>Done:</strong>
  <%= @chore.done %>
</p>

<p>
  <strong>User:</strong>
  <%= @chore.user_id %>
</p>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.email %></td>
        <td><%= client.address %></td>
        <td><%= client.notes %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KPC Dashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link href='http://fonts.googleapis.com/css?family=Dosis:400,600,200' rel='stylesheet' type='text/css'>
   
     <meta name="viewport" content="initial-scale=1">
     
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
</head>
<body>
<%= inline_svg "logo.svg", class: 'logo' %>


<%= yield %>

<footer>

</footer>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<div class="center">
<p>Please Login:</p>
<%= form_tag valid_path, method: "post" do %>
  <input id="name" type="text" placeholder="Email" name="user[email]" class="input">
  <input id="password" type="password" placeholder="Password" name="user[password]" class="input">
  <input type="submit"class="submit">
<%end%>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class="dashboard">
<div class="center">
<h1>
  <strong>
    Hey
    <%= @user.name %>!
  </strong>
</h1>
<a href = "<%= logout_path %>" class="submit3">log out</a> - <%= link_to 'Users', users_path, class:"submit3" %>

<br>
<div class="chores">
  
  <!-- add chore form -->
<div id="add_chore">
  <%= form_tag chores_path, :method => "post" do %>
  <p>
   <b> New Chore Name: </b>
    <br>
    <input type="text" class = "input" name="chore[name]" 
    required>
   <p><b> Task Manager:</b>
    <%@users = User.all %>
    <%@users.each do |user| %>
    <br><h2 class="radio"><input type="radio" name="chore[user_id]" value="<%= user.id %>"><%= user.name %></h2></div>
    <%end%>
    <br>
    <br>
    <p><b> Client:</b>
   
    <%@clients = Client.all %>
    <%@clients.each do |client| %>
    <br><h2 class="radio"><input type="radio" name="chore[client_id]" value="<%= client.id %>" class="radial"><%= client.name %></h2>
    <%end%>
    <input type="hidden" name="chore[done]" 
    value="false">
    <br>
    <input type="submit" value="submit" class="submit">
  
  </p>
  <%end%>
</div>
   <!-- add chore form -->
  
  
  <!-- chores to do -->
<%@chores = Chore.all %>
<h2>TODO</h2>
<%@chores.each do |chore| %>
<% if chore.done =="false" %>
<p>
 
  <%if chore.user.name == "Bryan" %>
  <%= inline_svg "bryan.svg", class: 'user_icon' %>
  <% end %>
  <%if chore.user.name == "Jeannie" %>
  <%= inline_svg "jeannie.svg", class: 'user_icon' %>
  <% end %>
  <%= chore.name %> <b><%= chore.client.name %> </b>
  <!-- client --> 
  <a href="<%= chore_path(chore.id) %>" data-method="put" class="submit2"> Mark as Done</a>&nbsp;
  <a href="<%=   chore_path(chore.id) %>" data-method="delete" class="submit2">delete</a>
</p>
<%end%>
<%end%>
<!-- chores done -->
<h2>DONE</h2>
<%@chores.each do |chore| %>
<% if chore.done =="true" %>
<p>
 
  <%if chore.user.name == "Bryan" %>
  <%= inline_svg "bryan.svg", class: 'user_icon' %>
  <% end %>
  <%if chore.user.name == "Jeannie" %>
  <%= inline_svg "jeannie.svg", class: 'user_icon' %>
  <% end %>
  <%= chore.name %> 
  <a href="<%= chore_path(chore.id) %>" data-method="put" class="submit2"> Mark as Todo</a>&nbsp;
  <a href="<%= chore_path(chore.id) %>" data-method="delete" class="submit2">delete</a>
</p>
<%end%>
<%end%>


</div>
</div>
</div>